
[tasks.dbuild]
run = "dagger call build"
description = "Build the project in dagger"

[tasks.publish]
run = "dagger call publish"
description = "Publish the project to ttl.sh"

[tasks.assemble]
run = "dagger call assemble --output=build/assemble"
description = "Publish the project, and assemble all manifests"

[tasks.push]
run = "git push"
depends = ["publish"]

[tasks.local]
run = "uv run python -m battlemaster"
sources = ["pyproject.toml", "battlemaster/**/*.py"]

[tasks.watch]
run = "mise watch --restart --jobs=1 local"

[tools]
python = "3.13"
uv = "latest"
